### ISSUE TITLE
Shots have no sound in the game

### ISSUE THREAD

**Issue by xcom169** [segrax/openfodder#22]
Shots are silent in the game. Is it the normal working?

**Comment by segrax** [comment]
Sound effects should definately be working, which game data are you using?

**Comment by xcom169** [comment]
A file from my dos copy.

Link: https://drive.google.com/open?id=1IVeksMpabVnODuJ6iJBm_AuMT7NaY2Zx

**Comment by segrax** [comment]
CF_ENG.DAT is normal for the DOS version, i havnt actually tested sound on Linux for awhile now, so i cant say for certain it works (but it did, and does on Windows at the moment)

Unfortunately i cant enable the sound card in my Linux VM for some unknown reason at the moment, so i also cant test it

**Comment by xcom169** [comment]
It's strange because music is working fine in Linux, just the the shot effects are silent.

**Comment by xcom169** [comment]
> It's strange because music is working fine in Linux, just the the shot effects are silent.

Cannon Fodder: CF_ENG.DAT Unknown MD5: FF878EB3DF61B1658BD6388855A2FACB

Unkown MD5 is an error message?

**Comment by xcom169** [comment]
> CF_ENG.DAT is normal for the DOS version, i havnt actually tested sound on Linux for awhile now, so i cant say for certain it works (but it did, and does on Windows at the moment)
> 
> Unfortunately i cant enable the sound card in my Linux VM for some unknown reason at the moment, so i also cant test it

Cannon Fodder: CF_ENG.DAT Unknown MD5: FF878EB3DF61B1658BD6388855A2FACB

MD5 unknown is a problem?

**Comment by segrax** [comment]
Hmm, it could be.. where did your version come from?

The GOG release (and original DOS CD ver) is EEB82D5A6B14E7E59C8F7B5169BFCD55

**Comment by segrax** [comment]
Ok,

I've tracked the problem back to the SDL2_Mixer library.

This commit altered the way it detects VOC files, and incorrectly altered the check from "Crea" to "CREA"

[https://hg.libsdl.org/SDL_mixer/comparison/92882ef2ab81/mixer.c](https://hg.libsdl.org/SDL_mixer/comparison/92882ef2ab81/mixer.c)

It was only just fixed ~5months ago, and the current official 2.0.2 release, was made prior to this fix (The Windows build is still using 2.0.1)

**Comment by segrax** [comment]
Closing as the issue is in the SDL2_Mixer library, 

I did try a cheap hack-around, but unfortunately a second check occurs when the VOC header is loaded, and this check is working correctly (altered the buffer stream to 'CREA' instead of 'Crea' prior to calling Mix_LoadWAV_RW, so it passes the initial type check, but fails when it actually attempts to load it as a VOC)
